In [126]:
import pandas as pd
import numpy as np

In [127]:
# help(pd.Series)

- DataFrame -> таблица
- Series -> колонки
- read_csv() -> читать из файла(csv)
- head() -> показать первые 5(по умолчанию) или n строк данных
- tail() -> показать последние 5(по умолчанию) или n строк данных
- describe() -> просмотр данных таблицы (mean, std, min, 25%, 50%(median), 75%, max)
- iloc() -> получение строки по номеру позиции
- loc() -> получение строки по имени индекса

In [128]:
my_index = ["Azerbaijan", "Usa", "Canada", "UK"]

In [129]:
my_data =[85, 20, 65, 78]

In [130]:
my_series = pd.Series(my_data, index=my_index)

In [131]:
my_series

Azerbaijan    85
Usa           20
Canada        65
UK            78
dtype: int64

In [132]:
my_series["Azerbaijan"]

np.int64(85)

In [133]:
ages = {"Nadir": 46, "Lorem": 125, "Ipsum": 25, "Sit Amet": 38}

In [134]:
pd.Series(ages)

Nadir        46
Lorem       125
Ipsum        25
Sit Amet     38
dtype: int64

In [135]:
q1 = {"Japan": 80, "China": 400, "India": 200, "USA": 250 }
q2 = { "China": 500, "Brazil": 100, "India": 210, "USA": 250 }

In [136]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [137]:
sales_q1

Japan     80
China    400
India    200
USA      250
dtype: int64

In [138]:
sales_q2

China     500
Brazil    100
India     210
USA       250
dtype: int64

In [139]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='str')

In [140]:
sales_q1 * 2

Japan    160
China    800
India    400
USA      500
dtype: int64

In [141]:
sales_q1 + sales_q2

Brazil      NaN
China     900.0
India     410.0
Japan       NaN
USA       500.0
dtype: float64

In [142]:
first_half = sales_q1.add(sales_q2, fill_value=0)
first_half

Brazil    100.0
China     900.0
India     410.0
Japan      80.0
USA       500.0
dtype: float64

In [143]:
my_columns = ["Jan", "Feb", "Mar"]

In [144]:
np.random.seed(42)
my_data = np.random.randint(0, 101, (4, 3))

In [145]:
df = pd.DataFrame(my_data, columns=my_columns, index=my_index)

In [146]:
df

            Jan  Feb  Mar
Azerbaijan   51   92   14
Usa          71   60   20
Canada       82   86   74
UK           74   87   99

In [147]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Azerbaijan to UK
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [148]:
employee_data_frame = pd.read_csv("data/employees.csv")
employee_data_frame

     ID      Name  Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy   56         USA   30854               15    Yes         IT
1     2  Victoria   46  Azerbaijan   68623               11    Yes         HR
2     3  Benjamin   32     Germany   37392               18     No  Marketing
3     4      Luna   25         USA   85680               13     No    Finance
4     5       Zoe   38      Brazil   76717                5    Yes     Design
..  ...       ...  ...         ...     ...              ...    ...        ...
95   96   Abigail   59         USA   52399               16    Yes    Finance
96   97    Harper   56         USA   76214               18    Yes         IT
97   98      Owen   58      France  116416                4     No     Design
98   99     Ethan   45         USA  100271                8    Yes     Design
99  100   Grayson   24     Germany   74064               11    Yes         HR

[100 rows x 8 columns]

In [149]:
employee_data_frame.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='str')

In [150]:
employee_data_frame.head(8)

   ID       Name  Age     Country  Salary  ExperienceYears Remote Department
0   1       Lucy   56         USA   30854               15    Yes         IT
1   2   Victoria   46  Azerbaijan   68623               11    Yes         HR
2   3   Benjamin   32     Germany   37392               18     No  Marketing
3   4       Luna   25         USA   85680               13     No    Finance
4   5        Zoe   38      Brazil   76717                5    Yes     Design
5   6  Sebastian   56       Japan  117092                5    Yes     Design
6   7    Paisley   36      France   80859               12     No    Finance
7   8      Jaxon   40  Azerbaijan   56309               18     No         HR

In [151]:
employee_data_frame.tail(2)

     ID     Name  Age  Country  Salary  ExperienceYears Remote Department
98   99    Ethan   45      USA  100271                8    Yes     Design
99  100  Grayson   24  Germany   74064               11    Yes         HR

In [152]:
employee_data_frame["Age"].mean()

np.float64(37.91)

In [153]:
employee_data_frame["Salary"].mean()

np.float64(72947.8)

In [154]:
employee_data_frame[employee_data_frame["Age"] > 50]

    ID       Name  Age     Country  Salary  ExperienceYears Remote Department
0    1       Lucy   56         USA   30854               15    Yes         IT
5    6  Sebastian   56       Japan  117092                5    Yes     Design
11  12      Riley   53         USA   82662               14    Yes  Marketing
12  13     Elijah   57      France   42688                0     No         IT
19  20     Evelyn   55      Brazil   64698               16     No  Marketing
27  28     Thomas   59         USA   79811               13     No     Design
32  33    Eleanor   54       Japan   41411                2    Yes         IT
36  37       Leah   56  Azerbaijan   38680                7    Yes         IT
48  49       Noah   52      Brazil   51918               15     No  Marketing
51  52       Ezra   53  Azerbaijan   60306                2     No         IT
52  53      Dylan   57  Azerbaijan   46646               17    Yes    Finance
56  57    Lillian   59      France   32049               12    Yes  Marketing
61  62   Isabella   51         USA  102694               15     No         IT
63  64      James   53         USA   37400               11     No    Finance
70  71       Lily   57      France   89040               19    Yes     Design
77  78       Ryan   58      France   91267                7     No    Finance
91  92       John   52     Germany   53328               12    Yes    Finance
92  93     Samuel   52      France  116831               17    Yes         IT
95  96    Abigail   59         USA   52399               16    Yes    Finance
96  97     Harper   56         USA   76214               18    Yes         IT
97  98       Owen   58      France  116416                4     No     Design

In [155]:
employee_data_frame["Country"].value_counts()

Country
USA           22
Azerbaijan    18
France        18
Brazil        17
Japan         14
Germany       11
Name: count, dtype: int64

In [156]:
employee_data_frame.groupby("Country")["Salary"].mean()

Country
Azerbaijan    72012.555556
Brazil        76001.882353
France        85016.111111
Germany       62115.000000
Japan         72384.214286
USA           67254.000000
Name: Salary, dtype: float64

In [157]:
employee_data_frame.index

RangeIndex(start=0, stop=100, step=1)

In [158]:
employee_data_frame.describe()

               ID         Age        Salary  ExperienceYears
count  100.000000  100.000000     100.00000       100.000000
mean    50.500000   37.910000   72947.80000         9.560000
std     29.011492   12.219454   27241.56386         6.075817
min      1.000000   18.000000   30854.00000         0.000000
25%     25.750000   26.750000   49860.50000         4.000000
50%     50.500000   38.000000   73540.00000        10.000000
75%     75.250000   46.250000   95972.25000        15.000000
max    100.000000   59.000000  119045.00000        19.000000

In [159]:
employee_data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,100.0,50.50,29.011492,1.0,25.75,50.5,75.25,100.0
Age,100.0,37.91,12.219454,18.0,26.75,38.0,46.25,59.0
Salary,100.0,72947.80,27241.563860,30854.0,49860.50,73540.0,95972.25,119045.0
ExperienceYears,100.0,9.56,6.075817,0.0,4.00,10.0,15.00,19.0

In [160]:
employee_data_frame["Country"]

0            USA
1     Azerbaijan
2        Germany
3            USA
4         Brazil
         ...
95           USA
96           USA
97        France
98           USA
99       Germany
Name: Country, Length: 100, dtype: str

In [161]:
employee_data_frame[["Country", "Name"]]

       Country      Name
0          USA      Lucy
1   Azerbaijan  Victoria
2      Germany  Benjamin
3          USA      Luna
4       Brazil       Zoe
..         ...       ...
95         USA   Abigail
96         USA    Harper
97      France      Owen
98         USA     Ethan
99     Germany   Grayson

[100 rows x 2 columns]

.drop(drop_data, axis, inplace) - axis (0-строки, 1-колонки), inplace(False- не изменяеть оригиналный DataFrame, True - изменяеть оригиналный DataFrame)

In [162]:
employee_data_frame.drop("Country", axis=1)
# employee_data_frame.drop("Country", axis=1, inplace=True)

     ID      Name  Age  Salary  ExperienceYears Remote Department
0     1      Lucy   56   30854               15    Yes         IT
1     2  Victoria   46   68623               11    Yes         HR
2     3  Benjamin   32   37392               18     No  Marketing
3     4      Luna   25   85680               13     No    Finance
4     5       Zoe   38   76717                5    Yes     Design
..  ...       ...  ...     ...              ...    ...        ...
95   96   Abigail   59   52399               16    Yes    Finance
96   97    Harper   56   76214               18    Yes         IT
97   98      Owen   58  116416                4     No     Design
98   99     Ethan   45  100271                8    Yes     Design
99  100   Grayson   24   74064               11    Yes         HR

[100 rows x 7 columns]

In [163]:
employee_data_frame

     ID      Name  Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy   56         USA   30854               15    Yes         IT
1     2  Victoria   46  Azerbaijan   68623               11    Yes         HR
2     3  Benjamin   32     Germany   37392               18     No  Marketing
3     4      Luna   25         USA   85680               13     No    Finance
4     5       Zoe   38      Brazil   76717                5    Yes     Design
..  ...       ...  ...         ...     ...              ...    ...        ...
95   96   Abigail   59         USA   52399               16    Yes    Finance
96   97    Harper   56         USA   76214               18    Yes         IT
97   98      Owen   58      France  116416                4     No     Design
98   99     Ethan   45         USA  100271                8    Yes     Design
99  100   Grayson   24     Germany   74064               11    Yes         HR

[100 rows x 8 columns]

In [164]:
employee_data_frame.drop(0, axis=0)

     ID       Name  Age     Country  Salary  ExperienceYears Remote Department
1     2   Victoria   46  Azerbaijan   68623               11    Yes         HR
2     3   Benjamin   32     Germany   37392               18     No  Marketing
3     4       Luna   25         USA   85680               13     No    Finance
4     5        Zoe   38      Brazil   76717                5    Yes     Design
5     6  Sebastian   56       Japan  117092                5    Yes     Design
..  ...        ...  ...         ...     ...              ...    ...        ...
95   96    Abigail   59         USA   52399               16    Yes    Finance
96   97     Harper   56         USA   76214               18    Yes         IT
97   98       Owen   58      France  116416                4     No     Design
98   99      Ethan   45         USA  100271                8    Yes     Design
99  100    Grayson   24     Germany   74064               11    Yes         HR

[99 rows x 8 columns]

In [165]:
employee_data_frame.shape

(100, 8)

In [166]:
employee_data_frame.set_index("Name", inplace=True)

In [167]:
employee_data_frame

           ID  Age     Country  Salary  ExperienceYears Remote Department
Name
Lucy        1   56         USA   30854               15    Yes         IT
Victoria    2   46  Azerbaijan   68623               11    Yes         HR
Benjamin    3   32     Germany   37392               18     No  Marketing
Luna        4   25         USA   85680               13     No    Finance
Zoe         5   38      Brazil   76717                5    Yes     Design
...       ...  ...         ...     ...              ...    ...        ...
Abigail    96   59         USA   52399               16    Yes    Finance
Harper     97   56         USA   76214               18    Yes         IT
Owen       98   58      France  116416                4     No     Design
Ethan      99   45         USA  100271                8    Yes     Design
Grayson   100   24     Germany   74064               11    Yes         HR

[100 rows x 7 columns]

In [169]:
employee_data_frame.loc["Zoe"]

ID                      5
Age                    38
Country            Brazil
Salary              76717
ExperienceYears         5
Remote                Yes
Department         Design
Name: Zoe, dtype: object

In [170]:
employee_data_frame.iloc[5]

ID                      6
Age                    56
Country             Japan
Salary             117092
ExperienceYears         5
Remote                Yes
Department         Design
Name: Sebastian, dtype: object